### ISSUE TITLE
Review EPCIS concepts for Location

### ISSUE THREAD

**Issue by dplumb94** [hyperledger/grid#304]
Review EPCIS concepts relating to BusinessLocation and ReadPoint to inform thinking on the Location RFC. Intent is to make sure we're well positioned for EPCIS support if that is the path we're going down.

**Comment by JessieZamzow** [comment]
Below findings are excerpts from the [GS1 EPCIS Guidelines](https://www.gs1.org/docs/epc/EPCIS_Guideline.pdf).

**General Summary**
The Where dimension of an EPCIS event captures where the event physically took place and/or where things are following the event. EPCIS events allow for two location types, `readPoint` and `businessLocation`. The `readPoint` is the location where the event took place. The `businessLocation` is the location where the object(s) is now considered to reside until a subsequent event takes place. Locations may be identified using a:
- [x] GS1 Global Location Number (GLN)
- [ ] GLN plus an extension
- [x] industry identifier other than GLN
- [x] geo-coordinates


URI syntax is used in EPCIS for the identifiers in the Where dimension. For example, suppose a location is identified by GLN 0614141111114 and extension 987. In EPCIS, the GLN+extension is represented as a Uniform Resource Identifier (URI) according to the EPC Tag Data Standard. The specific type of URI is called an SGLN, which is capable of representing either a
GLN+extension or a GLN without extension. The first part of this identifier (urn:epc:id:) indicates that this identifier follows the EPC Tag Data Standard. The next part (sgln:) says that it is either a GLN or GLN+extension (depending on whether the extension part is 0 or not).
- [ ] The SGLN for GLN 0614141111114 and extension 987 looks like this: urn:epc:id:sgln:0614141.11111.978.
- [x]  To represent a GLN without an extension, a single 0 digit is used in place of the extension, like this: urn:epc:id:sgln:0614141.11111.0. 

**Notes for our Futures Selves**
- The Grid Location RFC and implementation does not name the GLN extension component as in scope. At this time, GS1 recommends the use of GLN, not GLN + extension, for business transactions due to common limitations in transactional systems. Our current Grid design is not able to support the scenario where a `businessLocation` is defined at a fine level of granularity (i.e. a specific bin in a specific spot within a warehouse) via a GLN + extension. See [Transactional use of GLN extension component](https://www.gs1.org/1/glnrules/index.php/nid=176/lang=en).
